### ISSUE TITLE
Update Version and NPM

### ISSUE THREAD

**Issue by JREastonMarks** [tenodi/permission#7]
Hi,
Thank you for creating this great package and making my coding life much easier.

**ISSUE**
The source code currently in NPM is not the same as the one in this repo. Both versions say 1.0.4 but the code in NPM does not support user.role as an array while the code in the GitHub Repo does.

**WORKAROUND**
I was able to work around this issue temporarily by doing the following:

`npm install https://github.com/tenodi/permission`

Thanks!

**Comment by mylastore** [comment]
yes please UPDATE

**Comment by czytelny** [comment]
I bumped the version in the repository but, don't have rights to do so on npm...

**Comment by JREastonMarks** [comment]
@tenodi Could you update NPM?

Thanks!

**Comment by tenodi** [comment]
Will do so now.

**Comment by tenodi** [comment]
Done.

Sorry that I wasn't very active until now. I'm here now and will be checking this regularly.
